### ISSUE TITLE
感谢大佬的贡献，新需求：希望优化UI，优化自适应布局

### ISSUE THREAD

**Issue by miaoziguan** [a-nano-dust/dust-obsidian-calendar#10]
<img width="304" alt="image" src="https://github.com/a-nano-dust/dust-obsidian-calendar/assets/115944923/4f0e0292-126f-42a4-acb9-48b35db30ef9">
<img width="423" alt="image" src="https://github.com/a-nano-dust/dust-obsidian-calendar/assets/115944923/9d486aa3-9685-4723-bf46-8e26fc14b9a6">
或许，这三个元素可以放在一起，例如：2024年04月第2季度

**Comment by intime3000** [comment]
是的，如果宽度小一点，就会挤的很难看，甚至建议写“2024-04 夏季”，中国人都能看懂

**Comment by a-nano-dust** [comment]
> <img alt="image" width="304" src="https://private-user-images.githubusercontent.com/115944923/322258522-4f0e0292-126f-42a4-acb9-48b35db30ef9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzMTIxMzUsIm5iZiI6MTcxNjMxMTgzNSwicGF0aCI6Ii8xMTU5NDQ5MjMvMzIyMjU4NTIyLTRmMGUwMjkyLTEyNmYtNDJhNC1hY2I5LTQ4YjM1ZGIzMGVmOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMVQxNzE3MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NmQ3NjBkMzMyMGZlYjAxOWVlNWU2NGUxZjQ5M2FiZjYwMWQwMDkzNGRlODJlM2IzM2U1MTc5MzlkODkzYWZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-OZ4ByXnic2NVUX7iF2aNOZINFzH9wq7wLUULh7tZeU"> <img alt="image" width="423" src="https://private-user-images.githubusercontent.com/115944923/322259158-9d486aa3-9685-4723-bf46-8e26fc14b9a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzMTIxMzUsIm5iZiI6MTcxNjMxMTgzNSwicGF0aCI6Ii8xMTU5NDQ5MjMvMzIyMjU5MTU4LTlkNDg2YWEzLTk2ODUtNDcyMy1iZjQ2LThlMjZmYzE0YjlhNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMVQxNzE3MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MDBhYTY0YTgyZTFmYWJjMzJkYTQ5ZWQ2MWQ2YTZlOWY3OGQ5YzQ2MTU1ZDU1MTY2NDRmYTRlNGIyOGYyZmM4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.uRkv82r3eu2E4OgMqcJF95TmQcTDjZWDC7iX0fq0_lM"> 或许，这三个元素可以放在一起，例如：2024年04月第2季度

目前优化了布局效果，并且新增了自定义字体大小的功能，不会在出现这样的问题了

**Comment by a-nano-dust** [comment]
> 是的，如果宽度小一点，就会挤的很难看，甚至建议写“2024-04 夏季”，中国人都能看懂

新增了季度命名方式的设置项，可以将季度显示为春夏秋冬
