### ISSUE TITLE
建议结合template插件，支持模版

### ISSUE THREAD

**Issue by amacelite** [a-nano-dust/dust-obsidian-calendar#11]
目前在用calender插件，它结合了template插件，可以用模版，建议参考增加

**Comment by lisasuosuo** [comment]
非常需要template模板，求支持！！

**Comment by lisasuosuo** [comment]
看到这个问题一直没有得到回复，非常需要这个功能搭配，愿意付费支持

**Comment by yuzengbaocy** [comment]
可以在template插件里的add new folder template里添加设置一下，大体可用

**Comment by a-nano-dust** [comment]
不好意思，之前没有太多时间优化插件。模板功能我看有很多人需要，我会在下一个版本中支持，预计下周能完成。
