### ISSUE TITLE
双击不起作用

### ISSUE THREAD

**Issue by nyssance** [a-nano-dust/dust-obsidian-calendar#12]
无法创建日记，也没有任何提示，需要自己手动建文件夹和模板么？

**Comment by jdjshhc** [comment]
需要先在，插件里面的设置，有两步骤

1. 启动功能
2. 输入规则（可以参考虚影的格式设置，文件夹名称/新建的文件名称）

**Comment by nyssance** [comment]
可以创建了，怎么使用自己的模版呢？双击创建日记没有自动调用默认的模板。

**Comment by xzhjc5** [comment]
不能调用模板是一个缺陷

**Comment by a-nano-dust** [comment]
最新的 1.2.0 版本已经支持了模板

**Comment by nyssance** [comment]
我使用的是Templater，模版文件位于根目录下Tempaltes内，完整文件名是日记-tpl.md，我在配置中写入日记-tpl，不会有红色的警示提示，这样配置下，双击生成的还是空白文件。
我的模版含有一些远程拉取随机图片之类的异步方法，是Templater官方文档里有的那种，有影响么。

**Comment by a-nano-dust** [comment]
该功能已完成。 @nyssance 你的问题在 #40 中讨论
