### ISSUE TITLE
日记保存路径无法识别英文

### ISSUE THREAD

**Issue by dingzhw** [a-nano-dust/dust-obsidian-calendar#13]
开发者您好，
很酷的插件，农历的显示很有用！
但是日记保存路径似乎无法识别英文？还是有特殊的语法规则，我按照您给的链接查阅了`luxon`语法规则，但那都是关于时间、日期的，似乎没有关于文本字符如何处理？
希望这个问题能得到您的解答，谢谢！
![image](https://github.com/a-nano-dust/dust-obsidian-calendar/assets/22877281/3cbc2df4-2190-4a4f-b500-37a41b491af5)

**Comment by PandaNocturne** [comment]
+1

**Comment by PandaNocturne** [comment]
> 用单引号！

感谢感谢

**Comment by Moyf** [comment]
![image](https://github.com/a-nano-dust/dust-obsidian-calendar/assets/4013062/76f08279-f025-4103-a094-2bf8508a38fe)

感觉在文件命名规则这里可以加一行说明：
`如果需要保留纯英文字幕，用英文单引号将它们包裹起来，如： ‘Daily'/ `

**Comment by a-nano-dust** [comment]
使用单引号进行转义，已在描述中添加相关的说明
