### ISSUE TITLE
如果能获取decade，就更好了

### ISSUE THREAD

**Issue by ZHYX91** [a-nano-dust/dust-obsidian-calendar#14]
比如说，2024年是21世纪20年代，我希望将该年的日记，放在以下几个路径下：

1. 'diary'/2020s/2024
2. 'diary'/21st/2020s/2024
3. 'diary'/21th/2020s/2024

（2）和（3）有点麻烦，但希望（1）的”2020s“能够支持。

感谢！

**Comment by a-nano-dust** [comment]
luxon 暂不支持这种语法，短期内我还不想进行扩展
