### ISSUE TITLE
luxon无法设置以下日记格式

### ISSUE THREAD

**Issue by WuShaogui** [a-nano-dust/dust-obsidian-calendar#16]
![image](https://github.com/a-nano-dust/dust-obsidian-calendar/assets/24794718/e55a07db-5a20-4d73-ac96-c00e3a5e3b1c)

**Comment by WuShaogui** [comment]
add info

**Comment by a-nano-dust** [comment]
![Snipaste_2024-06-18_01-13-55](https://github.com/a-nano-dust/dust-obsidian-calendar/assets/113774866/dd061cbc-827e-4ab4-932b-fd8334c5a691)

1.4.0 版本开始已经支持了
