### ISSUE TITLE
通过商店安装失败

### ISSUE THREAD

**Issue by StrollStars** [a-nano-dust/dust-obsidian-calendar#17]
提示：No appropriate version found.

**Comment by a-nano-dust** [comment]
目前这个版本应该是没问题的，可以再试试

**Comment by StrollStars** [comment]
可以搜到了，感谢修复。

**Comment by StrollStars** [comment]
@a-nano-dust 版本信息如下，直接通过设置的社区插件市场安装，安装过程控制台无信息输出。
![image](https://github.com/a-nano-dust/dust-obsidian-calendar/assets/10942225/6ab9b436-67d7-40eb-9ca4-b0c1f3fffae9)

**Comment by a-nano-dust** [comment]
需要更新 Obsidian，插件要求 Obsidian 的最低版本是 1.5.12 @StrollStars

**Comment by StrollStars** [comment]
已安装成功
