### ISSUE TITLE
目录名BUG

### ISSUE THREAD

**Issue by allennany** [a-nano-dust/dust-obsidian-calendar#18]
![微信图片_20240506141040](https://github.com/a-nano-dust/dust-obsidian-calendar/assets/93176495/0bc64632-97a3-404e-bc72-e177537fde1f)

设定路径为：
400-Diary/日记/yyyy-MM
但是识别出来是：
400-2024/5/6iPMr2024/日记/2024-05

Diary 最后那个 y 识别错误了
a 给转成 PM 了
D y  都是日期语法

**Comment by lisasuosuo** [comment]
用单引号可以解决这个问题

**Comment by a-nano-dust** [comment]
使用单引号进行转义，1.2.1 版本开始在描述中对转义语法进行介绍
