### ISSUE TITLE
FR：增加对字数的大概显示

### ISSUE THREAD

**Issue by YIRU69** [a-nano-dust/dust-obsidian-calendar#21]
从 B 站上过来的，支持。
我一直在 ob 中写日记吧。日历是必须用的插件。
![image](https://github.com/a-nano-dust/dust-obsidian-calendar/assets/48148292/0dae2b19-6a1a-4a61-b56a-675af1198a63)
这是我使用的日历，希望作者可以完成这个功能。
大概就是如果日记中有 task 没有完成就会标注空心圆，如果日记中的字数每多200字，就会多显示一个实心圆。最多5个实心圆。

**Comment by a-nano-dust** [comment]
这个功能预计近期的版本中加上

**Comment by a-nano-dust** [comment]
1.3.0 版本中已完成该功能

**Comment by YIRU69** [comment]
@a-nano-dust 感谢作者

我在使用这个功能的时候，发现好像计算的字数不对，是否这个计算出了 yaml 区的字数？

我使用字数统计的插件计算的是1479字，但是插件计数的字数超过了 300*5=1500 字

![image](https://github.com/a-nano-dust/dust-obsidian-calendar/assets/48148292/dd01e82d-0e9c-40a0-b644-00800e7f965b)

**Comment by YIRU69** [comment]
我再次检查了一下，上图中的1479是包含 yaml 区的字数，插件中标点符号算吗？我感觉里面的字数计算可能需要检查一下

**Comment by a-nano-dust** [comment]
字数统计功能和 Obsidian 官方的逻辑是一样的
