### ISSUE TITLE
一个特殊需求/想法

### ISSUE THREAD

**Issue by Liutaorcn** [a-nano-dust/dust-obsidian-calendar#22]
感谢作者大大提供的插件！！！！！！！
我不懂技术，有个想法不知道能不能带来一些启发或者说能否实现呢？如图，我有几个项目都需要写日记、周记、月总结这样的，他们彼此需要隔离而不是在同一片笔记上做分段，又不想建立新的库（管理不便、同步不易）。有没有一种可能，可以预设多个存放路径（可能有不同的文件命名格式），而相对应的，在双击具体日期的时候（新建和查看）可以弹出这几个预设存放路径的选项。

上面是纯纯个人特殊需求的想法，还有几个正常的建议
1. 文字可以调小一点，或者提供可调整挡位设置？
2. 有没有可能，不用靠近显现左右调节的箭头这样的交互方式，右击菜单选择其实更好，这个菜单不一定是出现一个长条菜单，可以是只显示三个选项，更多的靠滚轮滚动，或者类似点击“今，月”的“月”一样，整个盘面变成月份选择器了（选年、选季度、选月份都可以统一这个操作逻辑嘛），“今 月”的“月”反而成了多余的存在，可以把“月”去掉，保留“今”留做跳转，把“今”字设计漂亮一点，还是一个小小点缀。主要不用左右箭头也可以，让你把年月季的显示更紧凑、好看一点（完全可以参考calendar嘛，不要全照着小米的样式来，那套搬过来看好像也没那么精致了）
3. 今天19号，看，那个蓝框选中的19，饱和度太高了，而且棱角重了点，因为提供了农历等信息，高饱和度看起来框和数字位置不协调，并且你这个框本身也确实有点太靠下了，往上调调，留白一点都没关系，我知道你靠下边的原因是什么，因为要提供一个写过日记的提示，我建议可以看小米的日历，日程提醒的小点是在日期的上方（同样的，饱和度和灰度值低一点），调整到上方刚好也解决了框和数字内容的包裹不协调的问题，完美。。。
4. 季度和周，可以给个选项不显示，有人就没有那个需求，整个那么大的季度在上面，也影响美观。周序号和日期之间也给个低灰度分隔线吧。
5. 模板，日记模板，周记模板这个一定是要有的，结合我最前面的想法，可能不同项目得有能设置不同的模板。
6. 周首日提供一下周日和周一的选择呗，严格来说周日为每周第一天呢
7. [2024-05-2024年5月21日]这个文件名怎么看怎么奇怪呢？
8. 体验时间较短，目前还没有其他想法了。继续。。。加油！！！作者大大。。。

<img width="947" alt="PixPin_2024-05-19_13-39-39" src="https://github.com/a-nano-dust/dust-obsidian-calendar/assets/121823345/d6dc0ae2-9984-43bd-97fd-b24717141b50">

---

2024.5.19 18：09 更新

试用了一会，发现作者大大 “今  月/年”处的设计还是没有毛病的，这里不做跳转用，而是做新建笔记用的。跳转是显隐的左右箭头完成，设计没毛病，只能说不高明，按钮太多也不美观，在**2024年，5月，2季度**这个标头显示的文字上利用**单击、双击**两个动作是可以完成这两项交互的吧......

---

2024.5.19 18：14 更新

那个被格式化的很奇怪的文件名，实际上是“**yyyy-MM-dd**”被分成了“**yyyy-MM**”和“**dd**”分别和格式化了一遍，不知道为什么显示正常了，我可以确定这个位置没有改动过，只是在改动前面**文件夹路径**部分的过程中，这里在一个我没在意的某个瞬间正常了，没精力复现，不知道哪里的问题

**Comment by a-nano-dust** [comment]
逐个回答一下：

1. 字体已经优化了，现在可以自定义大小；
2. 这样做是处于交互方面的考量，直接点箭头更方便；
3. UI 方面我确实没什么经验，所以希望路过的大佬能提一些更具体的需求，提前感谢了；
4. 季度和周的问题单开一条 issue 吧，放在这里不方便跟踪，UI 问题同上；
5. 模板功能已经实现了；
6. 这个可以考虑，也是再单开一条 issue；
7. 文件名可以根据个人习惯设置；
8. 感谢提出这么多建议，这个插件还会逐渐完善的。

**Comment by a-nano-dust** [comment]
第六天新开 issue 了，参见 #41

**Comment by a-nano-dust** [comment]
这条 issue 暂时关闭了，因为里面的内容太多了，如果有什么遗漏的地方，建议分条创建 issue
