### ISSUE TITLE
文件夹路径若有英文文件夹，如果出现`Format token`将和生成文件名格式一块，被格式化

### ISSUE THREAD

**Issue by Liutaorcn** [a-nano-dust/dust-obsidian-calendar#23]
<img width="625" alt="Obsidian_eharKtrzX6" src="https://github.com/a-nano-dust/dust-obsidian-calendar/assets/121823345/70e28130-a4a7-4d1d-b356-ccf77fc9d54b">

---
如图：这个**笔记文件生成路径**的格式，前面的**路径部分**如过出现英文也会被**格式化**。

**文件夹路径**和生成**文件名格式**，这二者能不能分开单独设置呢？目前显然是一块全部给格式化了。

---

2024.5.19 18：24 更新

刚刚试了一下将**英文文件夹路径**的部分：Dust Calender 用 **' '** 给包裹住，解决了问题，不过 **路径** 和 **文件名格式** 分开设置我觉得还是有必要的

**Comment by m1509001** [comment]
![image](https://github.com/a-nano-dust/dust-obsidian-calendar/assets/8222211/a14c7a87-5f24-4198-8964-3bb2501681b1)
确实图英文路径被解析，请修复

**Comment by a-nano-dust** [comment]
使用单引号可以进行转义，1.2.1 版本添加了对转义字符的介绍；
可变路径也是一个切实的需求，没必要将文件夹和文件名分开设置，太冗余了
