### ISSUE TITLE
双击新建笔记动作与某些场景下跳转动作冲突，带来不可控结果

### ISSUE THREAD

**Issue by Liutaorcn** [a-nano-dust/dust-obsidian-calendar#24]
![Obsidian_kdp1mrYAYb](https://github.com/a-nano-dust/dust-obsidian-calendar/assets/121823345/5702d1fb-39dc-47d6-9ce4-a63e9cd4ae9f)

---

如同GIF表现的那样，由于作者大大借鉴MIUI时期日历中做法：**补全显示每月首末两周空白的部分，且，单击可以跳转对应月份**，此逻辑与**双击新建笔记（日记/周记/月度笔记等）**逻辑发生冲突，在**双击动作**还未完成时，首先触发了**跳转**逻辑，且对于跳转后本应该是单击的动作依然识别为双击，在错误的日期建立了笔记（有点拗口，也就是这此位置，双击动作实际执行了三连击的结果）

**Comment by lbkyx** [comment]
> ![Obsidian_kdp1mrYAYb](https://private-user-images.githubusercontent.com/121823345/331861832-5702d1fb-39dc-47d6-9ce4-a63e9cd4ae9f.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3MDc1NTEsIm5iZiI6MTcxNjcwNzI1MSwicGF0aCI6Ii8xMjE4MjMzNDUvMzMxODYxODMyLTU3MDJkMWZiLTM5ZGMtNDdkNi05Y2U0LWE2M2U5Y2Q0YWU5Zi5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNlQwNzA3MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MDk3ZDEzZGRhMDdmOTg1NzY1ODNmMTAzNWM0NDNkZGJiMmI5NGY0YTE0YWMzYWRjMmYwNTM2MGExYWNhZDc1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PimDAK4U1XqhLQtYiR7YqpPPQIdwnQTtYh0mr1ekWFc) [ ![Obsidian_kdp1mrYAYb](https://private-user-images.githubusercontent.com/121823345/331861832-5702d1fb-39dc-47d6-9ce4-a63e9cd4ae9f.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3MDc1NTEsIm5iZiI6MTcxNjcwNzI1MSwicGF0aCI6Ii8xMjE4MjMzNDUvMzMxODYxODMyLTU3MDJkMWZiLTM5ZGMtNDdkNi05Y2U0LWE2M2U5Y2Q0YWU5Zi5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNlQwNzA3MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MDk3ZDEzZGRhMDdmOTg1NzY1ODNmMTAzNWM0NDNkZGJiMmI5NGY0YTE0YWMzYWRjMmYwNTM2MGExYWNhZDc1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PimDAK4U1XqhLQtYiR7YqpPPQIdwnQTtYh0mr1ekWFc) ](https://private-user-images.githubusercontent.com/121823345/331861832-5702d1fb-39dc-47d6-9ce4-a63e9cd4ae9f.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3MDc1NTEsIm5iZiI6MTcxNjcwNzI1MSwicGF0aCI6Ii8xMjE4MjMzNDUvMzMxODYxODMyLTU3MDJkMWZiLTM5ZGMtNDdkNi05Y2U0LWE2M2U5Y2Q0YWU5Zi5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNlQwNzA3MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MDk3ZDEzZGRhMDdmOTg1NzY1ODNmMTAzNWM0NDNkZGJiMmI5NGY0YTE0YWMzYWRjMmYwNTM2MGExYWNhZDc1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PimDAK4U1XqhLQtYiR7YqpPPQIdwnQTtYh0mr1ekWFc) [ ](https://private-user-images.githubusercontent.com/121823345/331861832-5702d1fb-39dc-47d6-9ce4-a63e9cd4ae9f.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3MDc1NTEsIm5iZiI6MTcxNjcwNzI1MSwicGF0aCI6Ii8xMjE4MjMzNDUvMzMxODYxODMyLTU3MDJkMWZiLTM5ZGMtNDdkNi05Y2U0LWE2M2U5Y2Q0YWU5Zi5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNlQwNzA3MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MDk3ZDEzZGRhMDdmOTg1NzY1ODNmMTAzNWM0NDNkZGJiMmI5NGY0YTE0YWMzYWRjMmYwNTM2MGExYWNhZDc1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PimDAK4U1XqhLQtYiR7YqpPPQIdwnQTtYh0mr1ekWFc)
> 
> 如同GIF表现的那样，由于作者大大借鉴MIUI时期日历中做法：**补全显示每月首末两周空白的部分，且，单击可以跳转对应月份**，此逻辑与**双击新建笔记（日记/周记/月度笔记等）逻辑发生冲突，在双击动作**还未完成时，首先触发了**跳转**逻辑，且对于跳转后本应该是单击的动作依然识别为双击，在错误的日期建立了笔记（有点拗口，也就是这此位置，双击动作实际执行了三连击的结果）

我也出现了

**Comment by a-nano-dust** [comment]
好的，这个问题会在想办法优化的

**Comment by a-nano-dust** [comment]
1.4.0 版本进行了优化，不会再出现这种问题了
