### ISSUE TITLE
README.md中“从 Obsidian 的社区插件来安装”有错误

### ISSUE THREAD

**Issue by lbkyx** [a-nano-dust/dust-obsidian-calendar#27]
B站上看到了视频，立马来体验，相当不错！
但是README.md中出现了`Image Toolkit`，这是不是属于是把别人的名字抄到自己的试卷上了[doge]

**Comment by a-nano-dust** [comment]
抄了 Image Toolkit 这款插件的介绍模式 :see_no_evil: 目前已经修复了

**Comment by a-nano-dust** [comment]
已解决，关闭这个问题
