### ISSUE TITLE
增加功能：可以有选择地关闭农历

### ISSUE THREAD

**Issue by jdjshhc** [a-nano-dust/dust-obsidian-calendar#32]
希望可以增加按钮可以关闭农历和假期休息这些信息，只保留日期就行。

1. 我个人是比较喜欢简单一点的，不需要太多信息展示，并且我可以在手机电脑其他的软件获取这些信息
2. 去掉的话，也有助于外国用户使用，他们应该也不太用得上这些

**Comment by jdjshhc** [comment]
但是你的插件可以很好地建立文件这点就很不错，比calendar这个老牌插件好用，应该会有很多人换的要是知道的话

**Comment by Moyf** [comment]
同样希望有这个开关 ❤️️

**Comment by a-nano-dust** [comment]
可以考虑，以后加上这个功能

**Comment by a-nano-dust** [comment]
1.4.0 版本已经支持了

**Comment by Moyf** [comment]
好耶！感谢开发~~
