### ISSUE TITLE
[FR] 希望增加「直接创建笔记」（不弹窗确认）的选项

### ISSUE THREAD

**Issue by Moyf** [a-nano-dust/dust-obsidian-calendar#39]
![image](https://github.com/a-nano-dust/dust-obsidian-calendar/assets/4013062/48f1090b-ab3e-49d8-9676-a04b0575ef2f)
类似  Calendar 插件的这个选项，可以直接创建，不经过二次确认。
平时 DailyNote 多的话这样会方便不少。

---

另外，希望增加「鼠标中键打开笔记」的功能，比起双击会更符合一些人的习惯。

**Comment by a-nano-dust** [comment]
禁止弹窗的功能后续可以加上；鼠标中键用起来比较麻烦，后续可以添加单击打开笔记的功能

**Comment by YIRU69** [comment]
@a-nano-dust 当我点击已经创建的文件时候，必须双击才可以打开，是否改成单击？

**Comment by a-nano-dust** [comment]
> @a-nano-dust 当我点击已经创建的文件时候，必须双击才可以打开，是否改成单击？

如果有需求的话，再另外提一个 issue 吧

**Comment by a-nano-dust** [comment]
1.4.0 版本允许禁用新建笔记的弹窗

**Comment by a-nano-dust** [comment]
1.4.0 版本允许禁用新建笔记的弹窗
