### ISSUE TITLE
Templater 模板不生效

### ISSUE THREAD

**Issue by a-nano-dust** [a-nano-dust/dust-obsidian-calendar#40]
我使用的是Templater，模版文件位于根目录下Tempaltes内，完整文件名是日记-tpl.md，我在配置中写入日记-tpl，不会有红色的警示提示，这样配置下，双击生成的还是空白文件。
我的模版含有一些远程拉取随机图片之类的异步方法，是Templater官方文档里有的那种，有影响么。

_Originally posted by @nyssance in https://github.com/a-nano-dust/dust-obsidian-calendar/issues/12#issuecomment-2148818232_

**Comment by a-nano-dust** [comment]
能否把你的模板内容发出来，如果涉及私人信息，可以大概写一个能够复现问题示例，方便我排查问题

**Comment by a-nano-dust** [comment]
能否把你的模板内容发出来，如果涉及私人信息，可以大概写一个能够复现问题示例，方便我排查问题

**Comment by nyssance** [comment]
---
cssclasses:
  - cover
prefer-view: read
created: <% tp.date.now() %>
tags:
  - 日记
  - timeline
  - me
---
![cover](<% tp.user.random_picture() %>)
# <% tp.file.title %>

<% tp.user.random_poetry() %>

**Comment by nyssance** [comment]
我又测试了下，我放一个没有任何功能的名为test.md模版，模版标题和内容里都不带任何中文，去掉所有函数，还是无法通过模版创建。应该是和Temlater的配合问题么？

**Comment by a-nano-dust** [comment]
![Snipaste_2024-06-08_00-20-31](https://github.com/a-nano-dust/dust-obsidian-calendar/assets/113774866/9ef43d14-7bf1-4d30-9462-9453804bc995)

![Snipaste_2024-06-08_00-20-39](https://github.com/a-nano-dust/dust-obsidian-calendar/assets/113774866/ffc9f898-d98e-4d18-b69a-ee7fbe79db5b)

![Snipaste_2024-06-08_00-20-53](https://github.com/a-nano-dust/dust-obsidian-calendar/assets/113774866/58cb63e9-b24e-49bd-b40d-b1df702dbf9e)

我测试了一下，是正常的。建议你用快捷键 Shift + i 打开控制台，看看有没有报错。令我我测试的时候发现这个拉取图片的代码会有延时，在内容刷新之前，需要确保光标在笔记输入区域内。

**Comment by a-nano-dust** [comment]
对，是这样

**Comment by a-nano-dust** [comment]
对，是这样
