### ISSUE TITLE
luxon语法的locale设置是不是有点问题……？

### ISSUE THREAD

**Issue by li0817** [a-nano-dust/dust-obsidian-calendar#46]
我想显示周三、周日这样的词汇，发现只支持英文
![image](https://github.com/a-nano-dust/dust-obsidian-calendar/assets/27659768/e4fd6a05-7c90-4ee7-9576-86eb03982077)

而如果使用`DDDD`，则显示正常
![image](https://github.com/a-nano-dust/dust-obsidian-calendar/assets/27659768/f7f133ee-5487-4a08-823c-304a82edacc0)

**Comment by a-nano-dust** [comment]
确实是这样，luxon 暂时还不支持单独显示一个星期三

**Comment by huddao** [comment]
同样，之前用官方日记插件的规则生成的格式是 `2024-06-12-星期三-W24`，现在只能生成数字或英语的星期，导致没办法识别到原来的日记文件

**Comment by huddao** [comment]
> 确实是这样，luxon 暂时还不支持单独显示一个星期三

那可以使用obsidian的日期生成规则吗，给个开关也好

**Comment by sasicDHH** [comment]
> > 确实是这样，luxon 暂时还不支持单独显示一个星期三
> 
> 那可以使用obsidian的日期生成规则吗，给个开关也好

确实有点刚需，也可能从其他地方打开日记，所以其他插件的日记规则都用ob最简单解决问题

**Comment by a-nano-dust** [comment]
是本地化配置的问题，之前我疏忽了。1.4.0 版本已经支持格式化输出中文了
