### ISSUE TITLE
希望颜色能跟随系统设置

### ISSUE THREAD

**Issue by miaoziguan** [a-nano-dust/dust-obsidian-calendar#48]
<img width="288" alt="image" src="https://github.com/a-nano-dust/dust-obsidian-calendar/assets/115944923/ee8dd742-27a1-4d36-ac1c-efb0ead1bdf9">
如图所示。希望颜色能跟随系统设置

**Comment by a-nano-dust** [comment]
可以再具体一点吗，你希望设计成什么效果

**Comment by miaoziguan** [comment]
就好比我的ob主题色是红色的，我希望calendar能跟随我的ob主题色的设置而变动

**Comment by a-nano-dust** [comment]
1.4.0 版本已经优化了样式，目前可以更好地适配不同的主题
