### ISSUE TITLE
文件命名规则

### ISSUE THREAD

**Issue by KleinBlue4685** [a-nano-dust/dust-obsidian-calendar#52]
我使用Log作为我的日记文件夹，但在dust calendar中设置Log/yyyy-MM-dd，显示的是6170g/yyyy-MM-dd，请问如何解决

**Comment by a-nano-dust** [comment]
![Snipaste_2024-06-18_21-58-33](https://github.com/a-nano-dust/dust-obsidian-calendar/assets/113774866/197122e3-199a-41ab-93a5-b59a44c887d7)

使用单引号进行转义即可
