### ISSUE TITLE
每日笔记文件命名有乱码

### ISSUE THREAD

**Issue by lifesign** [a-nano-dust/dust-obsidian-calendar#55]
如图，输入 `Calendar/每日总结/yyyy-MM-dd_W` ，结果 Calendar 部分变成了一串不对应的名字
<img width="801" alt="image" src="https://github.com/a-nano-dust/dust-obsidian-calendar/assets/2189610/b802ad2a-1813-456f-9751-7c43934388af">

**Comment by a-nano-dust** [comment]
英文名称需要转义，使用单引号即可，参考 #13
