### ISSUE TITLE
支持索引子目录下note

### ISSUE THREAD

**Issue by lifesign** [a-nano-dust/dust-obsidian-calendar#58]
因为记了几年笔记，虽然都放在`Calendar/每日总结`下，但只是当年的会这么平铺，其他的几年都是会人工归档到各自的年份目录，这就导致了在 dust calendar 前几年翻的时候，不会在对应的日期看到有记录
<img width="227" alt="image" src="https://github.com/a-nano-dust/dust-obsidian-calendar/assets/2189610/456437c3-594a-4f66-8bee-34c201dae225">

**Comment by a-nano-dust** [comment]
暂时支持不了，一种笔记只能支持一种路径
