### ISSUE TITLE
calendar建立的旧笔记链接不到，选择日期还是提示需要新建

### ISSUE THREAD

**Issue by barye81** [a-nano-dust/dust-obsidian-calendar#62]
calendar原来的日历，选择对应的日历时提示新建，calendar就可以打开原来的日历笔记

**Comment by a-nano-dust** [comment]
文件命名规则是否匹配呢

**Comment by barye81** [comment]
文件命名规则是匹配的，最近新建的都可以，原来的旧日历折叠到归档的文件夹，calendar可以打开，但是dust calendar打不开，应该是这个原因，是否可以链接上

**Comment by yanqswhu** [comment]
估计还是命名规则没有匹配上，我一开始把命名规则弄错了就匹配不上
